use sqlx::PgPool;

use newsletter::{configuration, startup, telemetry};

// Tip: install `cargo expand` to inspect the boilerplate code generated by the `tokio::main`
// procedural macro:
// 1. `rustup toolchain install nightly --allow-downgrade` (if not yet installed)
// 2. `cargo +nightly expand --bin newsletter`
#[tokio::main]
async fn main() -> std::io::Result<()> {
    // Sets telemetry up
    {
        let name = String::from("newsletter");
        let directives = "info";
        let make_writer = std::io::stdout;
        let subscriber = telemetry::get_subscriber(name, directives, make_writer);
        telemetry::init_subscriber(subscriber);
    }

    let config = configuration::parse().expect("Failed to parse the application config");

    let listener = config
        .server
        .listener()
        .expect("Failed to produce the application listener");

    let pool = PgPool::connect(&config.database.connection_string())
        .await
        .expect("Failed to connect to the database");

    if config.database.migrate {
        tracing::info!("Running database migrations");
        sqlx::migrate!("./migrations")
            .run(&pool)
            .await
            .expect("Failed to migrate the database");
    }

    startup::run_server(listener, pool)?.await
}
